### ISSUE TITLE
Feature: warn on less than two outputs

### ISSUE THREAD

**Issue by Mitchellpkt** [noncesense-research-lab/noncesense-explorer#2]
For a given transaction, IFF {condition} THEN {display warning}

### Condition: 

The transaction contains less than 2 outputs.

### Warning: 

This transaction has only one output, which (1) increases linkability risk, (2) reveals use of non-standard software, and (3) suggests that the transaction represents a wallet sweep or churn. 
 
### Reference

GitHub issue: [Enforce minimum of 2 outputs per transaction at the consensus level #5399](https://github.com/monero-project/monero/issues/5399)

### Example:

[2b2955caed0974f46b43e3ca83d1b47a14eddae402c5d47c44397b15fb05b2a2](https://xmrchain.net/tx/2b2955caed0974f46b43e3ca83d1b47a14eddae402c5d47c44397b15fb05b2a2)

**Comment by serhack** [comment]
Added one output warning. Tests needed to confirm it works.

**Comment by noncesense-research-lab** [comment]
Awesome, can check `2b2955caed0974f46b43e3ca83d1b47a14eddae402c5d47c44397b15fb05b2a2` (should show warning) and `ad8b224eb2d05b16782d0109734628abd28902a5a85ee8919209cbd827cd7ce6` (no warning)

-:- Isthmus

**Comment by serhack** [comment]
Confirmed it works.
