### ISSUE TITLE
Cosmetic: Update title from default value

### ISSUE THREAD

**Issue by Mitchellpkt** [noncesense-research-lab/noncesense-explorer#5]
Could be "Noncesense Explorer (Monero)" or something like that.

At some point I would like to also make a "Noncesense Explorer (Zcash)" that helps Zcash users identify fungibility defects in their transactions. 

The unifying theme would be that regardless of blockchain, *Noncesense Explorers*™ are your go-to for making sure that the wallet you're designing or downloading operates within parameters of the main anonymity pool.

Open to other ideas for naming. :- )

**Comment by serhack** [comment]
I would keep this repository only for Monero explorer. Why not calling this "esploristo" (Esperanto translation of explorer)?

**Comment by noncesense-research-lab** [comment]
I like esploristo :- )

**Comment by serhack** [comment]
:) Fantastic!
